### ISSUE TITLE
Support for rolling service updates

### ISSUE THREAD

**Issue by dsw9742** [docker-flow/docker-flow-monitor#55]
Question: does DFM support updates to services with [rolling policies](https://docs.docker.com/engine/swarm/swarm-tutorial/rolling-update/) (e.g. `--update-delay`) applied? We're seeing some unexpected results in our environment but want to see if this is by-design before filing a new feature or bug request.

**Comment by dsw9742** [comment]
Possibly related to the following issues:
* in Docker Flow Swarm Listener:
  * https://github.com/docker-flow/docker-flow-swarm-listener/issues/5
  * https://github.com/docker-flow/docker-flow-swarm-listener/issues/9
* in Docker for Linux:
  * https://github.com/docker/for-linux/issues/101
* in Moby:
  * https://github.com/moby/moby/issues/36834

**Comment by dsw9742** [comment]
@thomasjpfan we've got a test swarm with six nodes in it and cadvisor deployed globally as a service. It is created with `--update-parallelism=1` and `--update-delay=5s \` after DFSL and before DFM. Looking at the Prometheus /targets path after DFM is running, everything looks perfect for cadvisor - six replicas, one per node, as expected. When we issue a `service update` command for cadvisor, the service successfully completes its update, but we only see one replica registered at the /targets path in Prometheus. If we issue a `service rollback` command at that point, the service successfully completes its rollback, but we still only see one replica registered at /targets in Prometheus. We have also seen occurrences where the number of replicas was more than one but still less than six.

Honestly, the issue is manifesting itself in DFM but it might be that the root cause is in DFSL for all we know. I seem to recall seeing logic in DFSL that waits for tasks to converge ... any chance that logic only applies for service create commands rather than updates or rollbacks?

**Comment by dsw9742** [comment]
@thomasjpfan confirming the issue is not isolated to cadvisor as we've just reproduced it with node exporter service as well.

**Comment by thomasjpfan** [comment]
@dsw9742 Thanks for the information. I will look into this.

**Comment by thomasjpfan** [comment]
When you are updating the global service, are you updating the image?

**Comment by dsw9742** [comment]
Yes. Its a command to `docker service update --force --image [new image]`.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by thomasjpfan** [comment]
@dsw9742 I updated DFSL to address your issue. Please test out `dockerflow/docker-flow-swarm-listener:18.05.31-19` and see if it works for you.

**Comment by dsw9742** [comment]
@thomasjpfan thank you. Just tried this out. Good news and bad news. 

Bad news is all the updated targets appear to be sd_dns_configs, where they were previously sd_file_configs -- that means they lose all their special DF labeling. 

Good news is all the targets now appear in Prometheus after an update! 

And it may be that I've misconfigured DFSL in my test. I've set both `DF_SERVICE_POLLING_INTERVAL>5` and `DF_USE_DOCKER_SERVICE_EVENTS=true`. Perhaps only one or the other should be used in the current design?

**Comment by dsw9742** [comment]
OK, have tried the other two options as well. Here is what I've seen:
1. polling=0 and events=true : reverted to the previous scenario, whereupon `service update cadvisor --image [new image] --force` for the cadvisor deployed in `mode=global`, Prometheus goes from displaying one target for each node (so six in this setup) to only one target.
2. polling>0 and events=false : Prometheus picks up one target for each node (six). Excellent! However, now we have a different problem : it appears that polling requires DFSL be on the same overlay network as the target service (i.e. cadvisor in this test case) -- that isn't the case with Docker Events and I would argue should not be the case from an ideal standpoint, since its reasonable for admins/ops to desire as much network/service isolation as possible.
Lastly: given that this appears to be more of a DFSL issue than a DFM one, would you like me to close this issue here and re-create it under the DFSL repository?

**Comment by thomasjpfan** [comment]
Lets keep it here for now. This issue is using a feature in DFSL that is only used by DFM (`DF_INCLUDE_NODE_IP_INFO=true`).

1. Poling and events should be able to function at the same time.
2. This update should have fixed the polling=0 and events=true case. 
3. Having polling and events give different results is concerning.

@dsw9742  Can you post an example of your monitor stack?

**Comment by thomasjpfan** [comment]
@dsw9742 I am able to reproduce this issue. I will issue a fix soon.

**Comment by thomasjpfan** [comment]
There is a difference between updating a label and an image. Here is an example with 3 nodes:

1. `docker service update --label-add com.df.world=hello exporters_cadvisor` outputs:

```
overall progress: 3 out of 3 tasks 
upmrdnk09hqn: running   [==================================================>] 
n8emwnxrmvxi: running   [==================================================>] 
jv1m968id4ap: running   [==================================================>] 
verify: Service converged 
```

DFSL functions as expected, since it waits for all 3 instances to come online.

2. `docker service update --image google/cadvisor:v0.27.4 exporters_cadvisor` outputs:

```
overall progress: 1 out of 1 tasks 
upmrdnk09hqn: running   [==================================================>] 
verify: Service converged 
```

There is one task that converges. The instances on the other nodes will be updated according to your `--update-{delay,parallelism}` settings. DFSL only waits for the above task to converge, which means it will not be able to see the other instances get updated.

This is a tricky issue to resolve. 🤔

**Comment by dsw9742** [comment]
@thomasjpfan thank you for all of the investigating and legwork. 

Regarding your last sentence: does this imply the root cause lies within Docker itself (perhaps the previously-identified issues with Docker Events)?

A second thought: if events and polling are both supported now, should polling "correct" the problems that occur with events?

**Comment by thomasjpfan** [comment]
@dsw9742 

1. I think I figured out a fix for this issue with `dockerflow/docker-flow-swarm-listener:18.05.31-21`. Please try this release out and see if it works for you.

2. I added polling to make sure users had an option when the docker events api is misbehaving. I think its important to make sure everything functions with only the docker events api.

3. DFSL only needs to be on the same network as DFM. I have tested this out with the following stack files:

### monitor.yml

```yaml
version: "3"

services:

  monitor:
    image: dockerflow/docker-flow-monitor:${TAG:-latest}
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - GLOBAL_SCRAPE_INTERVAL=10s
      - ARG_ALERTMANAGER_URL=http://alert-manager:9093
      - DF_SCRAPE_TARGET_LABELS=env,metricType
      - DF_NODE_TARGET_LABELS=aws_region,role
      - DF_GET_NODES_URL=http://swarm-listener:8080/v1/docker-flow-swarm-listener/get-nodes
    networks:
      - monitor
      - exporter
    ports:
      - 9090:9090

  alert-manager:
    image: vfarcic/alert-manager:slack
    networks:
      - monitor

  swarm-listener:
    image: dockerflow/docker-flow-swarm-listener:18.05.31-21
    networks:
      - monitor
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://monitor:8080/v1/docker-flow-monitor/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://monitor:8080/v1/docker-flow-monitor/remove
      - DF_NOTIFY_CREATE_NODE_URL=http://monitor:8080/v1/docker-flow-monitor/node/reconfigure
      - DF_NOTIFY_REMOVE_NODE_URL=http://monitor:8080/v1/docker-flow-monitor/node/remove
      - DF_INCLUDE_NODE_IP_INFO=true
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  exporter:
    external: true
  monitor:
    external: true
```

### exporters.yml

```yaml
version: "3"

services:

  cadvisor:
    image: google/cadvisor
    networks:
      - exporter
    volumes:
      - /:/rootfs
      - /var/run:/var/run
      - /sys:/sys
      - /var/lib/docker:/var/lib/docker
    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: 15s
      labels:
        - com.df.notify=true
        - com.df.scrapePort=8080
        - com.df.scrapeNetwork=exporter
        - com.df.env=prod
        - com.df.metricType=system

networks:
  exporter:
    external: true
```

And running:

```bash
docker network create --driver overlay exporter
docker network create --driver overlay monitor
docker stack deploy -c monitor.yml monitor
docker stack deploy -c exporters.yml exporters
```

DFM and the exporters are on the exporter network. DFM and DFSL is on the monitor network. You will see that prometheus will start off with one target, but will get updated to include the other targets. This should work using polling and/or the docker events api.
